### ISSUE TITLE
Build failing because of missing package

### ISSUE THREAD

**Issue by kgrvamsi** [Masterminds/semver#129]
Hello,

I see the following issue when i try to build the code 

```
+ gb vendor fetch github.com/Masterminds/sprig

fetching recursive dependency github.com/Masterminds/goutils

fetching recursive dependency github.com/Masterminds/semver/v3

FATAL: command "fetch" failed: lstat /tmp/gb-vendor-596382780/v3: no such file or directory

FATAL: command "vendor" failed: exit status 1
```

Is there any change in the package?

**Comment by mattfarina** [comment]
That's a great question. I've not considered gb in some time.

semver v3 now uses Go modules which have been released (GA). semver is also at major version v3. Go modules requires (it fails if you don't) to have major versions as part of the package path after v1 (v2 and up). So, that /v3 on the end is the major version.

The wiki has a bunch of details on this at https://github.com/golang/go/wiki/Modules

One of the benefits of Go modules (which has nothing to do with package management but the change is bundled with it) is that projects can now be outside the `GOPATH` which is similar to gb. Since gb is about 2 years since a commit landed you might consider changing to Go modules.

**Comment by kgrvamsi** [comment]
We are moving to Go Modules but for now there is a project that needs to handle with gb as the package manager.

So @mattfarina if my project moves from gb to Go Modules way that this issue would be fixed?(I see that https://github.com/Masterminds/sprig/blob/master/go.mod declared the dependencies with v3 at the end)

**Comment by mattfarina** [comment]
@kgrvamsi yes, it would be fixed. The v3 release was shipped with Go modules in mind.

**Comment by mattfarina** [comment]
Closing as conversation ended over a year ago.
