### ISSUE TITLE
`20221209-update-renovatejson-v4` tag does not fail NewVersion test

### ISSUE THREAD

**Issue by bcbrockway** [Masterminds/semver#193]
Hi all, our ArgoCD Image Updater randomly changed one of our prod tags from v1.10.0 to a branch image - `20221209-update-renovatejson-v4`. They use the `NewVersion` function ([here](https://github.com/argoproj-labs/argocd-image-updater/blob/master/pkg/tag/tag.go#L161)) and we should probably petition them to add an option to use `StrictNewVersion` but should `NewVersion` really be accepting that tag as a valid semver?

**Comment by mattfarina** [comment]
@bcbrockway it looks like you found a bug.

**Comment by mattfarina** [comment]
It turns out I was wrong. From [the spec](https://semver.org/#spec-item-9):

>  Identifiers MUST comprise only ASCII alphanumerics and hyphens [0-9A-Za-z-]

If you read the [grammar](https://semver.org/#backusnaur-form-grammar-for-valid-semver-versions) you'll find the `-` explicitly listed for the `<non-digit>` cases.

A `-` is allowed. So, `NewVersion` should parse `20221209-update-renovatejson-v4` as valid while `StrictNewVersion` should provide an error.
