### ISSUE TITLE
Why would they be different?

### ISSUE THREAD

**Issue by qinmang** [Masterminds/semver#252]
This prints true:
```go
c, _ := semver.NewConstraint("<10.8.9")
v, _ := semver.NewVersion("10.2.3+dev")
fmt.Println(c.Check(v))
```
While this prints false:
```go
c, _ := semver.NewConstraint("<10.8.9")
v, _ := semver.NewVersion("10.2.3-dev")
fmt.Println(c.Check(v))
```
Why would they be different?

**Comment by mattfarina** [comment]
`10.2.3+dev` is the version `10.2.3` with build metadata of `dev`. Build metadata is not supposed to be used when dealing with precedence. So, `10.2.3+dev`, `10.2.3+foo`, and `10.2.3+bar` should all be seen with the same precedence. It's just build metadata on the version `10.2.3`.

`10.2.3-dev` is a pre-release of `10.2.3`. From the Semantic Version specification:

> Pre-release versions have a lower precedence than the associated normal version. A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version.

Because pre-release versions are unstable and might not satisfy compatibility requirements, many tools opt-in to including those versions. This library is included in that. Previous versions did not opt-in and it caused problems due to incompatibilities.

To opt-in, use a pre-release in the constraint.

**Comment by qinmang** [comment]
Thank you for your answer. I didn't consider the meanings represented by different symbols and the requirements for pre-release versions when using them. Since there were no specific guidelines for our use, the issues mentioned above occurred. Thanks for your explanation. I need to make some special handling to ensure compatibility during use.
