### ISSUE TITLE
Support for major-only constraint

### ISSUE THREAD

**Issue by marcelklehr** [Masterminds/semver#3]
hey,
thank you for creating this package!
It would be nice to achieve consistency with [npm's semver](https://npmjs.org/package/semver). Among other things this would include allowing omission of `x`s, e.g. `5` would be equivalent to `5.x`.

let me know what you think!

**Comment by technosophos** [comment]
I _think_ this is supported as long as you start with a `^` character, e.g. `^5.x`. The `^` tells SemVer to constrain to major release. I'll defer to @mattfarina, though.

**Comment by mattfarina** [comment]
@marcelklehr So, if I understand what you're suggesting we should have, as a constraint, `5`  be `5.x` instead of the `5.0.0` that it is today. Is that correct?

I can appreciate the interest in being the same as npm. I'll need to go back and look at how npm does things.

**Comment by mattfarina** [comment]
To add some more details on this space, here's some research:

* node-semver [does indeed turn a missing element into a wildcard](https://github.com/npm/node-semver/blob/master/README.md#x-ranges-12x-1x-12-).
* [Hashicorp/go-semver](https://github.com/hashicorp/go-version) goes the other way. [Missing elements are turned into 0](https://github.com/hashicorp/go-version/blob/2e7f5ea8e27bb3fdf9baa0881d16757ac4637332/version.go#L55). Though, it does not have the notion of a wildcard.
* [Composer](https://getcomposer.org) doesn't support strict semver but it's basically the idea. Composer doesn't support wildcards and under the hood is uses version_compare which essentially treats a missing element as 0.
* Elixr does work with [SemVer](http://elixir-lang.org/docs/stable/elixir/Version.html). It doesn't appear to support wildcards and replaces a missing element with a 0.
* Crates, for Rust, supports both [SemVer and wildcards](http://doc.crates.io/crates-io.html#using-cratesio-based-crates). It replaces a missing element with a 0 instead of a wildcard meaning you need to opt-in to wildcards.

**Comment by mattfarina** [comment]
Hat tip to @technosophos, here's some more detail on Composer. It does indeed support wildcards. Missing elements are replaced with 0. Wildcards are opt-in. You can even play with version ranges [here](http://semver.mwl.be/#?package=madewithlove%2Felasticsearcher&version=0.3.&minimum-stability=stable).

**Comment by marcelklehr** [comment]
Mh. ok, that's interesting! I think it's more liberal to turn missing elements into wildcards, while the alternative is more the conservative choice. For this library an option, how omissions should be treated, might be a solution, but I can understand if you oppose this request :)

**Comment by mattfarina** [comment]
Continuing my search:

* Ruby [Gemfiles](http://bundler.io/man/gemfile.5.html) do not appear to support wildcards and do turn a missing element into a 0. For example, 1.5 is 1.5.0.
* "It appears" that Python version numbers (used by things like pip) are SemVer compatible. See [PEP 0440](https://www.python.org/dev/peps/pep-0440/) and [PEP 0508](https://www.python.org/dev/peps/pep-0508). There are wildcards and it appears a missing element is replaced with a 0-ish setup rather than a wildcard. I could be wrong on this so please feel free to correct me.
* [github.com/coreos/go-semver](https://github.com/coreos/go-semver) and [github.com/blang/semver](https://github.com/blang/semver) don't allow for missing elements.

**Comment by mattfarina** [comment]
@marcelklehr I'm actually looking to make a well informed decision on this one. I had not thought about it beforehand and now that I am I wanted to be well informed on the space. And, I like to take notes on what I find for others (any myself in 6 months when I ask why I made this decision again).

**Comment by mattfarina** [comment]
After reviewing this space I think we should keep the current behavior of an empty spot defaulting to 0 instead of wildcard. This is for a few reasons:

1. npm appears to be the odd one out when it comes to defaulting to the wildcard. Others either default to 0 instead of a wildcard or default to 0 and don't support a wildcard.
2. It keeps compatibility with other Go libraries doing versions.
3. For those pulling this package on the tip of master instead of a version it won't cause an issue. Sure, they should pull a release version but this is Go and too many don't.
4. I think defaulting to 0 is more intuitive. In any case it's safer to keep the current expected behavior.

With that I'm going to close this issue.

@marcelklehr thanks for bringing this to my attention. I'm glad we looked into this, did the research, and thought it through.

**Comment by marcelklehr** [comment]
Thank you @mattfarina for taking the time to consider this request. I understand your decision and have since created a fork of your excellent library which is compatible with npm's semver (there were some additional issues I had to resolve). Cheers!
