### ISSUE TITLE
Constraints fail

### ISSUE THREAD

**Issue by scunningham** [Masterminds/semver#85]
It would appear that constraints fail when used with pre-release versions.  In particular, a pre-release is  considered newer incorrectly.  Program below against v1.4.2; output above:

----
3.3.0 < 5.0.0 == true
3.3.0 check(< 5.0.0) == true
3.3.0-47 < 5.0.0 == true
3.3.0-47 check(< 5.0.0) == false
3.3.0-47 is greater than or equal to 5.0.0
----

and the code:
```go
package main

import (
	"fmt"
	"github.com/Masterminds/semver"
)

func main() {

	tgt := semver.MustParse("5.0.0")

	// Simple constraint
	c := "< 5.0.0"
	cc, err := semver.NewConstraint(c)
	if err != nil {
		panic(err)
	}

	// Vanilla version
	sver := semver.MustParse("3.3.0")

	// Less than target, works as expected
	fmt.Printf("%v < %v == %v\n", sver, tgt, sver.LessThan(tgt))

	// Our vanilla version should also meet constraint
	fmt.Printf("%v check(%v) == %v\n", sver, c, cc.Check(sver))

	// Cool, let's create a version with a pre-release
	pver := semver.MustParse("3.3.0-47")

	// Less than target, works as expected
	fmt.Printf("%v < %v == %v\n", pver, tgt, pver.LessThan(tgt))

	// But the constraint, umm umm
	fmt.Printf("%v check(%v) == %v\n", pver, c, cc.Check(pver))

	// Let's ask why
	_, errs := cc.Validate(pver)
	for _, e := range errs {
		fmt.Println(e)
	}
}
```

**Comment by mattfarina** [comment]
@scunningham While I've not yet run your code I can explain the reason. `3.3.0-47` is a pre-release. [According to the spec](https://semver.org/#spec-item-9):

> A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version.

The pre-release of `3.3.0-47` may not be API consistent with `3.3.0` and there are often changes between pre-releases that break APIs.

The issue here is the inconsistent handling. That's due to the pre-release handling being added on after the fact so as not to break the API to this package. We need to clean this up in a v2 to make the things consistent.

**Comment by mattfarina** [comment]
I just looked things over, including what others are doing, and updated the docs.

The comparisons on `Version` are spec compliant to comparisons and always include prereleases. The spec part is at https://semver.org/#spec-item-11.

The constraints different tools use, like npm/js, cargo/rust, and composer/php use are not to any standard and are different. Because prereleases are not expected to be API compliant to releases they are typically ignored. That is what the `-47` is in the examples. Those are prereleases rather than stable releases. There is no one method for ignoring those.

The constraints here will ignore those by default but have an opt-in similar to other tools like js.

The docs have been updated to detail all of this.
